### ISSUE TITLE
Free trial link not working 

### ISSUE THREAD

**Issue by 5fq** [MicrosoftDocs/connected-spaces#11]
The free trial under "What is Next " is getting redirected to same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88164c34-b81c-2b71-e3ed-63f40841e38f
* Version Independent ID: 36b7f41e-aa13-ffb9-316c-fbe861b06eb3
* Content: [Overview of Dynamics 365 Connected Spaces Preview](https://learn.microsoft.com/en-us/dynamics365/connected-spaces/)
* Content Source: [articles/index.md](https://github.com/MicrosoftDocs/connected-spaces/blob/main/articles/index.md)
* Service: **dynamics-365-connected-spaces**
* GitHub Login: @alissapolucha
* Microsoft Alias: **alissag**

**Comment by m-hartmann** [comment]
Apologies for the late reply. This product has been deprecated. Trials are no longer available. I'm closing this issue for housekeeping reasons. 

Thanks, 
Michael
