### ISSUE TITLE
Does non work email really work?

### ISSUE THREAD

**Issue by Izmiyash** [MicrosoftDocs/connected-spaces#7]
[Enter feedback here]
this page is saying "You can enter a non-work email address and we will create an account and tenant for you." though, trial process does not accept non work email. 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/39150572/155104370-d760bf59-520f-4cc2-a585-f8a0c1c350aa.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59dd3a09-44de-295e-9120-71482346696d
* Version Independent ID: 59dd3a09-44de-295e-9120-71482346696d
* Content: [Trial FAQ - Dynamics 365 Connected Spaces Preview](https://docs.microsoft.com/en-us/dynamics365/connected-spaces/trial-faq)
* Content Source: [articles/trial-faq.md](https://github.com/MicrosoftDocs/connected-spaces/blob/main/articles/trial-faq.md)
* Service: **dynamics-365-connected-spaces**
* GitHub Login: @alwinv
* Microsoft Alias: **alwinv**

**Comment by BryceHolmes** [comment]
Hi. Does this address the issue you experienced when trying to sign up with non-work email address: https://docs.microsoft.com/en-us/dynamics365/connected-spaces/trial-signup-admin

**Comment by Izmiyash** [comment]
Nope

**Comment by BryceHolmes** [comment]
Hi. We ended up modifying the instructions based on the issue you reported. You can find the updated instructions here: https://docs.microsoft.com/en-us/dynamics365/connected-spaces/trial-signup
